require "fileutils"
require "json"
require "tempfile"

class Secrets
  HEADER = [
    "# Generated by mise manager:secrets from 1Password.",
    "# Update secrets in 1Password, then run mise manager:secrets to regenerate.",
    "# Local changes will be overwritten.",
    "",
  ].join("\n").freeze
  ENVIRONMENT = /\A[a-z0-9_-]+\z/
  KEY = /\A[A-Za-z_][A-Za-z0-9_]*\z/
  TEMPLATE_KEY = /\A([A-Za-z_][A-Za-z0-9_]*)=/
  REFERENCE = %r{\Aop://([^/]+)/([^/]+)\z}

  def initialize(shell: SpawnShell.new, output: $stdout)
    @shell = shell
    @output = output
  end

  def call
    Settings.all.fetch(:secrets, {}).each do |environment, reference|
      environment = environment.to_s
      raise "Invalid secrets key: #{environment}" unless environment.match?(ENVIRONMENT)

      if reference.blank?
        @output.puts "Skipping .env.#{environment}: secrets.#{environment} is not set in config.json."
        next
      end

      write(environment, render(item(reference)))
    end
  end

  private

  def item(reference)
    match = reference.match(REFERENCE)
    raise "Invalid 1Password item reference: #{reference}" unless match

    JSON.parse(
      @shell.capture("op", "item", "get", match[2], "--vault", match[1], "--format", "json", "--reveal"),
    )
  end

  def render(item)
    fields = item.fetch("fields", []).reject { |field| field["purpose"] == "NOTES" }
    keys = fields.map { |field| field["label"].to_s }
    invalid_keys = keys.grep_v(KEY)
    raise "Invalid secret field labels in #{item["title"]}: #{invalid_keys.join(", ")}" if invalid_keys.present?

    duplicate_keys = keys.tally.select { |_key, count| count > 1 }.keys
    raise "Duplicate secret field labels in #{item["title"]}: #{duplicate_keys.join(", ")}" if duplicate_keys.present?

    values = fields.to_h { |field| [ field["label"], field["value"].to_s ] }
    template = File.read(File.join(File.dirname(Settings.path), ".env.default")).lines(chomp: true)
    template_keys = template.filter_map { |line| line[TEMPLATE_KEY, 1] }
    lines = template.filter_map do |line|
      key = line[TEMPLATE_KEY, 1]
      next line unless key
      next unless values.key?(key)

      "#{key}=#{quoted(key, values.fetch(key))}"
    end
    extra_keys = values.keys - template_keys
    lines += [ "" ] + extra_keys.map { |key| "#{key}=#{quoted(key, values.fetch(key))}" } if extra_keys.present?
    "#{HEADER}\n#{lines.map { |line| "#{line}\n" }.join}"
  end

  def write(environment, contents)
    root = File.dirname(Settings.path)
    path = File.join(root, ".env.#{environment}")
    file = Tempfile.create(".env.#{environment}.", root)
    begin
      file.chmod(0600)
      file.write(contents)
      file.close
      File.rename(file.path, path)
    ensure
      file.close unless file.closed?
      FileUtils.rm_f(file.path)
    end
    @output.puts "Wrote .env.#{environment}"
  end

  def quoted(key, value)
    return "'#{value}'" unless value.include?("'")
    raise "Secret #{key} cannot contain both ' and `" if value.include?("`")

    escaped = value.gsub(/[\\\"$]/) { |character| "\\#{character}" }
    "\"#{escaped}\""
  end
end
