require_relative "test_helper"
require "stringio"

class SecretsTestShell
  attr_reader :commands

  def initialize(items)
    @items = items
    @commands = []
  end

  def capture(*command)
    @commands << command
    JSON.generate(@items.fetch(command.fetch(3)))
  end
end

class SecretsTest < Minitest::Test
  def setup
    @root = File.dirname(Settings.path)
    @output = StringIO.new
    File.write(
      File.join(@root, ".env.default"),
      "RAILS_ENV=xxx\nMISSING=xxx\n\nDEPLOY_SSH_KEY=xxx\nSPECIAL=xxx\nQUOTE=xxx\n\n# ---\n",
    )
    @items = {
      "Code Moto Development" => {
        "title" => "Code Moto Development",
        "fields" => [
          { "id" => "notesPlain", "label" => "notesPlain", "purpose" => "NOTES", "value" => "OLD=value" },
          { "id" => "a", "label" => "EXTRA", "type" => "CONCEALED", "value" => "extra" },
          { "id" => "b", "label" => "SPECIAL", "type" => "CONCEALED", "value" => "a\"b$c`d\\e" },
          { "id" => "f", "label" => "QUOTE", "type" => "CONCEALED", "value" => "it's \"$x\" \\" },
          { "id" => "c", "label" => "DEPLOY_SSH_KEY", "type" => "CONCEALED", "value" => "first-line\nsecond-line" },
          { "id" => "d", "label" => "RAILS_ENV", "type" => "CONCEALED", "value" => "development" },
          { "id" => "e", "label" => "EMPTY", "type" => "CONCEALED", "section" => { "id" => "more" } },
        ],
      },
      "Code Moto Production" => {
        "title" => "Code Moto Production",
        "fields" => [
          { "id" => "a", "label" => "RAILS_ENV", "type" => "CONCEALED", "value" => "production" },
        ],
      },
    }
    @shell = SecretsTestShell.new(@items)
  end

  def test_writes_each_environment_from_its_item_fields
    write_secrets(
      development: "op://Projects/Code Moto Development",
      production: "op://Projects/Code Moto Production",
    )

    Secrets.new(shell: @shell, output: @output).call

    assert_equal(
      [
        "# Generated by mise manager:secrets from 1Password.",
        "# Update secrets in 1Password, then run mise manager:secrets to regenerate.",
        "# Local changes will be overwritten.",
        "",
        "RAILS_ENV='development'",
        "",
        "DEPLOY_SSH_KEY='first-line",
        "second-line'",
        %q(SPECIAL='a"b$c`d\e'),
        %q(QUOTE="it's \"\$x\" \\\\"),
        "",
        "# ---",
        "",
        "EXTRA='extra'",
        "EMPTY=''",
        "",
      ].join("\n"),
      File.read(File.join(@root, ".env.development")),
    )
    assert_equal(
      "#{Secrets::HEADER}\nRAILS_ENV='production'\n\n\n# ---\n",
      File.read(File.join(@root, ".env.production")),
    )
    assert_equal 0600, File.stat(File.join(@root, ".env.development")).mode & 0777
    assert_equal(
      [
        %w[op item get] + [ "Code Moto Development" ] + %w[--vault Projects --format json --reveal],
        %w[op item get] + [ "Code Moto Production" ] + %w[--vault Projects --format json --reveal],
      ],
      @shell.commands,
    )
    assert_equal "Wrote .env.development\nWrote .env.production\n", @output.string
    assert_equal [ ".env.default", ".env.development", ".env.production" ], Dir.children(@root).grep(/\A\.env/).sort
  end

  def test_overwrites_an_existing_file
    write_secrets(development: "op://Projects/Code Moto Development")
    File.write(File.join(@root, ".env.development"), "STALE=value\n")

    Secrets.new(shell: @shell, output: @output).call

    refute_includes File.read(File.join(@root, ".env.development")), "STALE"
  end

  def test_skips_blank_references
    write_secrets(development: "", production: nil)

    Secrets.new(shell: @shell, output: @output).call

    assert_empty @shell.commands
    refute File.exist?(File.join(@root, ".env.development"))
    assert_includes @output.string, "Skipping .env.development: secrets.development is not set in config.json."
    assert_includes @output.string, "Skipping .env.production: secrets.production is not set in config.json."
  end

  def test_does_nothing_without_secrets
    Secrets.new(shell: @shell, output: @output).call

    assert_empty @shell.commands
    assert_empty @output.string
  end

  def test_rejects_an_invalid_environment
    write_secrets("../bad": "op://Projects/Code Moto Development")

    error = assert_raises(RuntimeError) { Secrets.new(shell: @shell, output: @output).call }

    assert_equal "Invalid secrets key: ../bad", error.message
    assert_empty @shell.commands
  end

  def test_rejects_a_field_reference
    write_secrets(development: "op://Projects/Code Moto Development/notesPlain")

    error = assert_raises(RuntimeError) { Secrets.new(shell: @shell, output: @output).call }

    assert_equal "Invalid 1Password item reference: op://Projects/Code Moto Development/notesPlain", error.message
    assert_empty @shell.commands
  end

  def test_rejects_invalid_field_labels
    @items.fetch("Code Moto Development").fetch("fields") << { "label" => "NOT VALID", "value" => "x" }
    @items.fetch("Code Moto Development").fetch("fields") << { "label" => "", "value" => "x" }
    write_secrets(development: "op://Projects/Code Moto Development")

    error = assert_raises(RuntimeError) { Secrets.new(shell: @shell, output: @output).call }

    assert_equal "Invalid secret field labels in Code Moto Development: NOT VALID, ", error.message
    refute File.exist?(File.join(@root, ".env.development"))
  end

  def test_rejects_duplicate_field_labels
    @items.fetch("Code Moto Development").fetch("fields") << { "label" => "RAILS_ENV", "value" => "x" }
    write_secrets(development: "op://Projects/Code Moto Development")

    error = assert_raises(RuntimeError) { Secrets.new(shell: @shell, output: @output).call }

    assert_equal "Duplicate secret field labels in Code Moto Development: RAILS_ENV", error.message
    refute File.exist?(File.join(@root, ".env.development"))
  end

  def test_rejects_a_value_with_single_quotes_and_backticks
    @items.fetch("Code Moto Development").fetch("fields") << { "label" => "BAD", "value" => "it's `x`" }
    write_secrets(development: "op://Projects/Code Moto Development")

    error = assert_raises(RuntimeError) { Secrets.new(shell: @shell, output: @output).call }

    assert_equal "Secret BAD cannot contain both ' and `", error.message
    refute File.exist?(File.join(@root, ".env.development"))
  end

  private

  def write_secrets(secrets)
    config = JSON.parse(File.read(Settings.path))
    File.write(Settings.path, JSON.generate(config.merge("secrets" => secrets)))
  end
end
